"""how an agent action was graded

Revision ID: 0275dbbd0a15
Revises: 25f5e142c9bf
Create Date: 2026-09-27 11:00:36.786866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0275dbbd0a15'
down_revision: Union[str, Sequence[str], None] = '25f5e142c9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_column('detail')

    # ### end Alembic commands ###
