"""job summaries and suggested rules

Revision ID: 25f5e142c9bf
Revises: 6128f395be46
Create Date: 2026-09-27 10:32:53.322446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f5e142c9bf'
down_revision: Union[str, Sequence[str], None] = '6128f395be46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion', sa.Text(), nullable=False))

    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_column('summary')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('suggestion')

    # ### end Alembic commands ###
