"""oversight, ledger, hash-chained audit

Revision ID: 6128f395be46
Revises: 78ca6e189484
Create Date: 2026-09-27 08:17:45.603311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6128f395be46'
down_revision: Union[str, Sequence[str], None] = '78ca6e189484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=False),
    sa.Column('systems', sa.JSON(), nullable=False),
    sa.Column('price_per_action_usd', sa.Float(), nullable=False),
    sa.Column('monthly_fee_usd', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_handle'), ['handle'], unique=True)

    op.create_table('ledger',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('action_id', sa.String(length=40), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('playbook_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('basis', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('minutes_saved', sa.Float(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('settled_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_status'), ['status'], unique=False)

    op.create_table('agent_actions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=True),
    sa.Column('trigger_event_id', sa.String(length=40), nullable=True),
    sa.Column('conformance', sa.Float(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=False),
    sa.Column('reworked', sa.Boolean(), nullable=False),
    sa.Column('rework_event_id', sa.String(length=40), nullable=True),
    sa.Column('rework_by', sa.String(length=120), nullable=True),
    sa.Column('human_grade', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('settled_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_verdict'), ['verdict'], unique=False)

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('hash', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_hash'), ['hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_hash'))
        batch_op.drop_column('hash')
        batch_op.drop_column('prev_hash')

    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_verdict'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_ts'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_agent_id'))

    op.drop_table('agent_actions')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_status'))
        batch_op.drop_index(batch_op.f('ix_ledger_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_created_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_action_id'))

    op.drop_table('ledger')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_handle'))

    op.drop_table('agents')
    # ### end Alembic commands ###
