"""lessons and covers

Revision ID: 78ca6e189484
Revises: e8316e36389b
Create Date: 2026-09-11 23:24:23.624863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ca6e189484'
down_revision: Union[str, Sequence[str], None] = 'e8316e36389b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('backup', sa.String(length=120), nullable=False),
    sa.Column('until', sa.Float(), nullable=False),
    sa.Column('promoted', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_covers_actor'), ['actor'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=False),
    sa.Column('draft_id', sa.String(length=40), nullable=True),
    sa.Column('trigger_text', sa.Text(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('actual_text', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.Float(), nullable=True),
    sa.Column('answered_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_status'))
        batch_op.drop_index(batch_op.f('ix_lessons_playbook_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_covers_actor'))

    op.drop_table('covers')
    # ### end Alembic commands ###
