"""initial schema

Revision ID: e8316e36389b
Revises: 
Create Date: 2026-09-11 22:49:59.093190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8316e36389b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)

    op.create_table('audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_ts'), ['ts'], unique=False)

    op.create_table('automations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.Float(), nullable=True),
    sa.Column('next_run_at', sa.Float(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('max_writes_per_hour', sa.Integer(), nullable=False),
    sa.Column('max_usd_per_day', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('system', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('thread_key', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_system'), ['system'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_thread_key'), ['thread_key'], unique=False)
        batch_op.create_index('ix_events_thread_ts', ['thread_key', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_created_at'), ['created_at'], unique=False)

    op.create_table('playbooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('system', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('consistency', sa.Float(), nullable=False),
    sa.Column('median_latency_s', sa.Float(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('drafts_total', sa.Integer(), nullable=False),
    sa.Column('drafts_scored', sa.Integer(), nullable=False),
    sa.Column('drafts_hit', sa.Integer(), nullable=False),
    sa.Column('score_sum', sa.Float(), nullable=False),
    sa.Column('approvals', sa.Integer(), nullable=False),
    sa.Column('rejections', sa.Integer(), nullable=False),
    sa.Column('executions', sa.Integer(), nullable=False),
    sa.Column('undos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('stage_changed_at', sa.Float(), nullable=False),
    sa.Column('stage_history', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_stage'), ['stage'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('principal', sa.String(length=120), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=False),
    sa.Column('principal', sa.String(length=120), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('tx_status', sa.String(length=20), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=True),
    sa.Column('draft_id', sa.String(length=40), nullable=True),
    sa.Column('replay_of', sa.String(length=40), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_principal'), ['principal'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('seen',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('due', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('done_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('actions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('undo', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('undone_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_run_id'), ['run_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=80), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('principal', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('decided_at', sa.Float(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('playbook_id', sa.String(length=40), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=40), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('actual_event_id', sa.String(length=40), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_detail', sa.JSON(), nullable=False),
    sa.Column('human_grade', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('resolved_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_playbook_id'), ['playbook_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_drafts_playbook_id'))
        batch_op.drop_index(batch_op.f('ix_drafts_created_at'))

    op.drop_table('drafts')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_run_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_run_id'))

    op.drop_table('actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    op.drop_table('tasks')
    op.drop_table('settings')
    op.drop_table('seen')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_principal'))
        batch_op.drop_index(batch_op.f('ix_runs_created_at'))

    op.drop_table('runs')
    op.drop_table('policies')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_stage'))

    op.drop_table('playbooks')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_created_at'))

    op.drop_table('memories')
    op.drop_table('meetings')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index('ix_events_thread_ts')
        batch_op.drop_index(batch_op.f('ix_events_thread_key'))
        batch_op.drop_index(batch_op.f('ix_events_system'))
        batch_op.drop_index(batch_op.f('ix_events_kind'))
        batch_op.drop_index(batch_op.f('ix_events_actor'))

    op.drop_table('events')
    op.drop_table('budgets')
    op.drop_table('automations')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_action'))

    op.drop_table('audit')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
